version: '3.0'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeper
    ports:
      - "2181:2181"
    healthcheck:
      test: nc -z zookeeper 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    links:
      - zookeeper
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # For local usage you need to define the LOCAL_IP variable with the value of Ethernet adapter Ethernet IPv4 Address or replace here
      - KAFKA_ADVERTISED_HOST_NAME=${LOCAL_IP}
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CREATE_TOPICS=TestTopic:1:1
      #- LOG4J_LOGGER_KAFKA=TRACE,kafkaAppender
    volumes:
      - "./docker/check-topics.sh:/project/check-topics.sh"
    healthcheck:
      test: ["CMD-SHELL", "chmod u+x /project/check-topics.sh && /project/check-topics.sh TestTopic"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 10s